name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'  

    - name: Show Go version
      run: go version

    - name: List directory contents
      run: ls -al

    - name: Build
      run: go build -v q1.go

    - name: Test
      run: go test -v ./...
